name: Build docker image

on:
  push:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone submodules
      run: |
        git submodule init
        git submodule update

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: perchunpak
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: perchunpak/fitcrack
        flavor: |
          latest=true
        # semantic versions in another workflow
        tags: |
          type=raw,value=dev

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
